SchoolMgmt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('', include(('student.urls', 'student'), namespace='student')),
    path('', include(('teacher.urls', 'teacher'), namespace='teacher')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

school/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import *
from school.views import CustomLoginView, RegisterUser, AdminHome
from student.views import StudentAttendanceView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AdminHome.as_view(), name='admin_home'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('attendance/', StudentAttendanceView.as_view(), name='attendance')
]

student/urls.py
from django.urls import path

from student.views import StudentCreateView, StudentHome, StudentDeleteView, StudentListView, StudentUpdateView

urlpatterns = [
    path('student/', StudentHome.as_view(), name='student_home'),
    path('student/list/', StudentListView.as_view(), name='student_list'),
    path('student/<int:id>/', StudentListView.as_view(), name='student_detail'),
    path('student/create/', StudentCreateView.as_view(), name='student_create'),
    path('student/<int:roll_no>/update/', StudentUpdateView.as_view(), name='student_update'),
    path('student/<pk>/delete/', StudentDeleteView.as_view(), name='student_delete'),
]

teacher/urls.py
from django.urls import path

from teacher.views import TeacherHome, TeacherCreateView, TeacherListView, TeacherDetailView, TeacherUpdateView, \
    TeacherDeleteView, TeacherAttendanceView

urlpatterns = [
    path('teacher/', TeacherHome.as_view(), name='teacher_home'),
    path('teacher/create/', TeacherCreateView.as_view(), name='teacher_create'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher/attendance/', TeacherAttendanceView.as_view(), name='teacher_attendance'),
    path('teacher/<str:emp_id>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher/<str:emp_id>/update/', TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher/<str:emp_id>/delete/', TeacherDeleteView.as_view(), name='teacher_delete'),

]

school/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

USER_TYPE_CHOICE = (
    ('s', 'student'),
    ('t', 'teacher'),
    ('a', 'admin')
)


class CustomUser(AbstractUser):
    dob = models.DateField(null=True, blank=True)
    mobile_no = models.CharField(max_length=13,null=True, blank=True)
    photo = models.ImageField(upload_to='user_images/', null=True, blank=True)
    type_of_user = models.CharField(max_length=2, choices= USER_TYPE_CHOICE , default= 'a')
    is_user_deleted = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.username

school/forms.py
from django import forms

from school.common_models import Address, Attendance, ClassName
from school.models import CustomUser


# class RegistrationForm(UserCreationForm):
#     dob = forms.DateField(widget=forms.SelectDateWidget())
#     class Meta:
#         model = CustomUser
#         fields = [ 'first_name', 'last_name', 'username', 'password1', 'password2',
#                    'dob','email', 'mobile_no', 'photo', 'type_of_user'
#
#         ]

class RegistrationForm(forms.ModelForm):
    dob = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model = CustomUser
        fields = [ 'first_name', 'last_name', 'username',
                   'dob','email', 'mobile_no', 'photo', ]


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['user',]


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        fields = '__all__'

school/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.forms import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import CreateView
from school.forms import RegistrationForm
from school.models import CustomUser


class RegisterUser(CreateView):
    form_class = RegistrationForm
    model = CustomUser
    template_name = 'registration/registration.html'

    success_url = reverse_lazy('school:register')


class CustomLoginView(LoginView):

    def home(self):
        user = self.request.user
        if user.type_of_user == 't':
            return HttpResponseRedirect(reverse('teacher:teacher_home'))
        elif user.type_of_user == 's':
            return HttpResponseRedirect(reverse('student:student_home'))
        else:
            return HttpResponseRedirect(reverse('school:admin_home'))

    def form_valid(self, form):
        user = form.get_user()
        if not user.password:
            forms.ValidationError('Password cannot be Null')
        login(self.request, user)

        return self.home()

    def save_user(self, user):
        self.request.session['otp_user'] = user

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return self.home()
        else:
            return super().get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return self.home()
        else:
            return super().post(self, request, *args, **kwargs)


class AdminHome(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'school/admin_home.html')


class AttendenceView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(request, 'school/attendance.html')

school/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>School Management</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="text-center">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">{%block title %}{% endblock %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}

                {% if user.type_of_user == "a" %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'school:admin_home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teacher:teacher_create' %}">Create Teacher</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student:student_create' %}">Create Student</a>
                    </li>
                {% endif %}

                {% if user.type_of_user == 't' %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'teacher:teacher_home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'school:attendance' %}">Add Attendance</a>
                    </li>
                {% endif %}

                {% if user.type_of_user == 's' %}

                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'school:logout' %}">Logout</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}

<script src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>