SchoolMgmt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('school.urls', 'school'), namespace='school')),
    path('', include(('student.urls', 'student'), namespace='student')),
    path('', include(('teacher.urls', 'teacher'), namespace='teacher')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

school/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import *
from school.views import CustomLoginView, RegisterUser, AdminHome
from student.views import StudentAttendanceView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AdminHome.as_view(), name='admin_home'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('attendance/', StudentAttendanceView.as_view(), name='attendance')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <style>
            table, th, td {
                width: 50%;
                background-color: #f1f1c1;
                border: 1px solid black;
                border-collapse: collapse;
                margin: 0 100px;
        }
        th, td {
            padding: 15px;
        }
        th{
        background-color: #eee;
        }
        {% block style %}

        {% endblock %}

    </style>

    <script>
            {% block script%}
            {%endblock%}
    </script>
</head>

<body>
    {% block content %}
<br>
<a href="{% url 'school:logout' %}">Logout</a>
{% if user.is_autheticated %}
<a href="{% url 'school:logout' %}">Logout</a>
{%else%}
<a href="{% url 'school:login' %}">Login</a>
{%endif%}
    {% endblock %}



</body>
</html>